version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 1
    versioning-strategy: increase
    schedule:
      interval: "weekly"
    groups:
      lint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint"
          - "eslint-*"
          - "prettier"
          - "tslint"
          - "tslint-*"
    ignore:
      - dependency-name: "material-components-web"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@stencil/core"
        update-types: ["version-update:semver-major"]
      - dependency-name: "jest"
      - dependency-name: "jest-cli"
      - dependency-name: "@types/jest"
      - dependency-name: "puppeteer"
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
