# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      lodash:
        patterns:
          - "lodash"
          - "lodash-es"
      vite:
        patterns:
          - "vite"
          - "vite-plugin-pwa"
          - "@vitejs/*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      semantic-release:
        patterns:
          - "semantic-release"
          - "@semantic-release/*"
      remark:
        patterns:
          - "react-markdown"
          - "remark-*"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      actions:
        patterns:
          - "actions/*"
