/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface AppHome {

    }
  }

  interface HTMLAppHomeElement extends StencilComponents.AppHome, HTMLStencilElement {}

  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-home': JSXElements.AppHomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHomeAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppRoot {

    }
  }

  interface HTMLAppRootElement extends StencilComponents.AppRoot, HTMLStencilElement {}

  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
  }
  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-root': JSXElements.AppRootAttributes;
    }
  }
  namespace JSXElements {
    export interface AppRootAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface PdButton {
      'disabled': boolean;
      'label': string;
      'primary': boolean;
      'selected': boolean;
    }
  }

  interface HTMLPdButtonElement extends StencilComponents.PdButton, HTMLStencilElement {}

  var HTMLPdButtonElement: {
    prototype: HTMLPdButtonElement;
    new (): HTMLPdButtonElement;
  };
  interface HTMLElementTagNameMap {
    'pd-button': HTMLPdButtonElement;
  }
  interface ElementTagNameMap {
    'pd-button': HTMLPdButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'pd-button': JSXElements.PdButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface PdButtonAttributes extends HTMLAttributes {
      'disabled'?: boolean;
      'label'?: string;
      'primary'?: boolean;
      'selected'?: boolean;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
