name: Website Up Check

on:
  schedule:
    # Runs once a day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-website-content:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set Up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Puppeteer
      run: |
        rm -f package-lock.json
        echo "{}" > package.json
        npm install puppeteer

    - name: Check Website Content
      run: node .github/workflows/check-website.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Ping healthchecks.io on Success
      if: success()
      run: |
        curl --retry 5 https://hc-ping.com/ebd07d7c-e104-490f-b339-2d5ed71c3aa9

    - name: Close Open Issues on Success
      if: success()
      run: |
        ISSUE_TITLE="🚨 APP DOWN 🚨: Website Content Check Failed"
        ENCODED_ISSUE_TITLE=$(echo -n "$ISSUE_TITLE" | jq -sRr @uri)
        SEARCH_URL="https://api.github.com/search/issues?q=repo:pocket-dragon/pocket-dragon.github.io+type:issue+state:open+in:title+${ENCODED_ISSUE_TITLE}"
        echo "Calling $SEARCH_URL"
        ISSUES=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" "$SEARCH_URL" | jq -r '.items[].number')

        for ISSUE_NUMBER in $ISSUES
        do
          CLOSE_URL="https://api.github.com/repos/pocket-dragon/pocket-dragon.github.io/issues/$ISSUE_NUMBER"
          DATA='{"state": "closed"}'

          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" \
                -d "$DATA" "$CLOSE_URL"
          echo "Closed issue #$ISSUE_NUMBER"
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Send Explicit Fail to healthchecks.io on Failure
      if: failure()
      run: |
        curl --retry 3 https://hc-ping.com/ebd07d7c-e104-490f-b339-2d5ed71c3aa9/fail

    - name: Create Issue on Failure
      if: failure()
      run: |
        ISSUE_TITLE="🚨 APP DOWN 🚨: Website Content Check Failed"
        ISSUE_BODY="Automated check failed. The expected content was not found on the page."
        API_URL="https://api.github.com/repos/pocket-dragon/pocket-dragon.github.io/issues"
        DATA=$(jq -n --arg title "$ISSUE_TITLE" --arg body "$ISSUE_BODY" '{title: $title, body: $body}')

        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" \
             -d "$DATA" "$API_URL"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


